---
- name: Setup an apache2 on n2 server
  hosts: n2
  become: yes


  tasks:
  - name: updating the local package index to reflect the latest upstream changes
    apt: 
      name: update
      state: present
  
  
  - name: Install apache2
    apt: 
      name: apache2
      state: present

  - name: Start apache2
    service: 
      name: apache2
      state: started

  - name: Enable apache2
    service:
      name: apache2
      enabled: true
...


